// import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: 101,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-birthday-wish-personalized-small-pillow-cushion-146213-m.jpg",
    name: "Cuddly Birthday Personalised Cushion",
    reviews: 5,
    rating: 3.5,
    price: "425",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: true,
  },
  {
    _id: 102,
    image:
      "https://www.fnp.com/images/pr/x/v20220518140334/dazzling-birthday-surprise_1.jpg",
    name: "Dazzling Birthday Surprise",
    reviews: 100,
    rating: 4,
    price: "2457",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: false,
  },
  {
    _id: 103,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-birthday-fiesta-personalized-led-cushion-203987-m.jpg",
    name: "Birthday Fiesta Personalized LED Cushion",
    reviews: 10,
    rating: 3,
    price: "945",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: true,
  },
  {
    _id: 104,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-personalized-blue-leather-wallet-for-men-178483-m.jpg",
    name: "Personalized Blue Leather Wallet for Men",
    reviews: 3,
    rating: 4.5,
    price: "895",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: false,
  },
  {
    _id: 105,
    image:
      "https://www.fnp.com/images/pr/x/v20230321171904/sip-of-love-birthday-mug-hand-delivery_1.jpg",
    name: "Sip of Love Birthday Mug",
    reviews: 80,
    rating: 4.1,
    price: "399",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: true,
  },
  {
    _id: 106,
    image:
      "https://www.fnp.com/images/pr/x/v20230105004901/sprinkle-of-premium-chocolates_1.jpg",
    name: "Sprinkle Of Premium Chocolates",
    reviews: 10,
    rating: 3.4,
    price: "1099",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: false,
  },
  {
    _id: 107,
    image:
      "https://www.fnp.com/images/pr/x/v20220926144952/personalised-birthday-special-led-speaker_1.jpg",
    name: "Personalised Birthday Special LED Lamp Speaker",
    reviews: 72,
    rating: 5,
    price: "799",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: true,
  },
  {
    _id: 108,
    image:
      "https://www.fnp.com/images/pr/x/v20210123022616/beautiful-cadbury-dairy-milk-gift_1.jpg",
    name: "Beautiful Cadbury Dairy Milk Gift",
    reviews: 8,
    rating: 4.8,
    price: "1049",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: false,
  },
  {
    _id: 109,
    image:
      "https://www.fnp.com/images/pr/x/v20191206193209/personalised-name-black-bottle_1.jpg",
    name: "Personalised Black Name Bottle",
    reviews: 199,
    rating: 4.6,
    price: "499",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: true,
  },
  {
    _id: 110,
    image:
      "https://www.fnp.com/images/pr/x/v20210224171900/wildhorn-mens-classy-wallet-combo-black_1.jpg",
    name: "Wildhorn Mens Classy Wallet Combo Black",
    reviews: 16,
    rating: 2,
    price: "999",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: false,
  },
  {
    _id: 111,
    image:
      "https://www.fnp.com/images/pr/x/v20221012175339/spider-plant-cylindrical-vase-terrarium_1.jpg",
    name: "Spider Plant Cylindrical Vase Terrarium",
    reviews: 6,
    rating: 5,
    price: "649",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: false,
  },
  {
    _id: 112,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-kinda-sweet-personalized-travel-mug-133090-m.jpg",
    name: "Kinda Sweet Personalized Travel Mug",
    reviews: 9,
    rating: 3.9,
    price: "795",
    discount: 30,
    categoryName: "anniversary",
    newArrival: true,
    trending: false,
  },
  {
    _id: 113,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-photo-cake-for-anniversary-half-kg--133106-m.jpg",
    name: "Photo Cake for Anniversary",
    reviews: 7,
    rating: 1,
    price: "895",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: false,
  },
  {
    _id: 114,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-personalized-wooden-block-candles-110426-m.jpg",
    name: "Personalized Wooden Block Candles",
    reviews: 25,
    rating: 3.9,
    price: "525",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: true,
  },
  {
    _id: 115,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-personalized-dark-brown-croc-embossed-leather-wallet-131831-m.jpg",
    name: "Personalized Dark Brown Croc Embossed Leather Wallet",
    reviews: 30,
    rating: 3.3,
    price: "625",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: false,
  },
  {
    _id: 116,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-colorful-personalized-rotating-crystal-cube-with-led-46756-m.jpg",
    name: "Colorful Personalized Rotating Crystal Cube with LED",
    reviews: 26,
    rating: 3.8,
    price: "5000",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: false,
  },

  {
    _id: 117,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-beautiful-bunch-of-15-white-roses-61470-m.jpg",
    name: "Beautiful Bunch of 15 White Roses",
    reviews: 6,
    rating: 2.5,
    price: "1245",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: true,
  },
  ,
  {
    _id: 118,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-floral-hearts-openable-cz-pendant-152910-m.jpg",
    name: "Floral Hearts Openable CZ Pendant",
    reviews: 27,
    rating: 4.3,
    price: "5000",
    discount: 30,
    categoryName: "anniversary",
    newArrival: true,
    trending: false,
  },

  {
    _id: 119,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-personalized-purple-agate-stone-coasters-206189-m.jpg",
    name: "Personalized Purple Agate Stone Coasters",
    reviews: 10,
    rating: 4.1,
    price: "895",
    discount: 30,
    categoryName: "anniversary",
    newArrival: true,
    trending: false,
  },

  {
    _id: 120,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-personalized-stylish-rose-gold-adjustable-women-s-ring-206670-m.jpg",
    name: "Personalized Stylish Rose Gold Adjustable Women's Ring",
    reviews: 30,
    rating: 3.5,
    price: "245",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: true,
  },

  {
    _id: 121,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-romantic-personalized-photo-keychain-109911-m.jpg",
    name: "Personalized Photo Keychain",
    reviews: 20,
    rating: 4,
    price: "395",
    discount: 30,
    categoryName: "anniversary",
    newArrival: true,
    trending: true,
  },

  {
    _id: 122,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-dreamcatcher-inspired-oxidised-anklet-135952-m.jpg",
    name: "Dreamcatcher Inspired Oxidised Anklet",
    reviews: 24,
    rating: 4.2,
    price: "245",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: true,
  },

  {
    _id: 123,
    image:
      "https://www.fnp.com/images/pr/x/v20200628183105/the-unxplored-wooden-blocks_1.jpg",
    name: "The Unxplored Wooden Blocks",
    reviews: 20,
    rating: 4.4,
    price: "699",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: true,
  },

  {
    _id: 124,
    image:
      "https://www.fnp.com/images/pr/x/v20220902182229/led-solar-happy-quote-mason-jar_1.jpg",
    name: "LED Solar Happy Quote Mason Jar",
    reviews: 50,
    rating: 4,
    price: "699",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 125,
    image:
      "https://www.fnp.com/images/pr/x/v20200628182835/lcd-writing-tablet_5.jpg",
    name: "LCD Writing Tablet",
    reviews: 10,
    rating: 4.5,
    price: "599",
    discount: 30,
    categoryName: "unique",
    newArrival: true,
    trending: true,
  },

  {
    _id: 126,
    image:
      "https://www.fnp.com/images/pr/x/v20230117192317/pink-rose-tea-pot-arrangement_1.jpg",
    name: "Pink Rose Tea Pot Arrangement",
    reviews: 10,
    rating: 4.6,
    price: "1649",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 127,
    image:
      "https://www.fnp.com/images/pr/x/v20221006185342/rocher-bloom-rectangular-box_1.jpg",
    name: "Rocher Bloom Rectangular Box",
    reviews: 2,
    rating: 5,
    price: "2599",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 128,
    image:
      "https://www.fnp.com/images/pr/x/v20220902182231/set-of-3-led-candles-with-remote_1.jpg",
    name: "Set Of 3 LED Candles With Remote",
    reviews: 2,
    rating: 4,
    price: "849",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: true,
  },

  {
    _id: 129,
    image:
      "https://www.fnp.com/images/pr/x/v20230113114644/panda-3d-mug-with-lid-spoon_1.jpg",
    name: "Panda 3D Mug With Lid Spoon",
    reviews: 7,
    rating: 4.3,
    price: "749",
    discount: 30,
    categoryName: "unique",
    newArrival: true,
    trending: false,
  },

  {
    _id: 130,
    image:
      "https://www.fnp.com/images/pr/x/v20220117163017/personalised-engraved-wooden-tic-tac-toe_1.jpg",
    name: "Personalised Engraved Wooden Tic Tac Toe",
    reviews: 5,
    rating: 4,
    price: "1499",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 131,
    image:
      "https://www.fnp.com/images/pr/x/v20220209182935/astronaut-magnetic-car-phone-holder_1.jpg",
    name: "Astronaut Magnetic Car Phone Holder",
    reviews: 1,
    rating: 5,
    price: "499",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 132,
    image:
      "https://www.fnp.com/images/pr/x/v20230412172217/personalised-name-birth-flower-necklace_1.jpg",
    name: "Personalised Name Birth Flower Necklace",
    reviews: 2,
    rating: 3.5,
    price: "2599",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: true,
  },

  {
    _id: 133,
    image:
      "https://www.fnp.com/images/pr/x/v20210119025151/beautiful-personalised-photos-heartagon_1.jpg",
    name: "Beautiful Personalised Photos Heartagon",
    reviews: 9,
    rating: 5,
    price: "1547",
    discount: 30,
    categoryName: "unique",
    newArrival: false,
    trending: false,
  },

  {
    _id: 134,
    image:
      "https://www.fnp.com/images/pr/x/v20230117192315/peach-roses-and-asiatic-lily-in-handle-basket_1.jpg",
    name: "Peach Roses & White Lilies Handle Basket",
    reviews: 15,
    rating: 4,
    price: "5449",
    discount: 30,
    categoryName: "unique",
    newArrival: true,
    trending: false,
  },
  {
    _id: 135,
    image:
      "https://www.fnp.com/images/pr/x/v20220506110013/white-and-silver-birthday-balloon-arrangement_1.jpg",
    name: "White & Silver Birthday Balloon Arrangement",
    reviews: 7,
    rating: 4,
    price: "1299",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: false,
  },
  {
    _id: 136,
    image:
      "https://www.fnp.com/images/pr/x/v20210415130941/led-photo-clip-string-lights-10-leds_1.jpg",
    name: "LED Photo Clip String Lights",
    reviews: 12,
    rating: 3.9,
    price: "299",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: false,
  },
  {
    _id: 137,
    image:
      "https://www.fnp.com/images/pr/x/v20220926144954/personalised-birthday-wishes-table-clock_1.jpg",
    name: "Personalised Birthday Wishes Table Clock",
    reviews: 61,
    rating: 4.2,
    price: "525",
    discount: 30,
    categoryName: "birthday",
    newArrival: false,
    trending: false,
  },
  {
    _id: 138,
    image:
      "https://www.fnp.com/images/pr/x/v20221114184908/personalised-birthday-wishes-multi-photo-frame_4.jpg",
    name: "Personalised Birthday Wishes Multi Photo Frame",
    reviews: 60,
    rating: 4.6,
    price: "5000",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: true,
  },
  {
    _id: 139,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-unique-personalized-photo-pop-up-box-109828-m.jpg",
    name: "Unique Personalized Photo Pop-up Box",
    reviews: 38,
    rating: 4.5,
    price: "495",
    discount: 30,
    categoryName: "anniversary",
    newArrival: false,
    trending: false,
  },
  {
    _id: 140,
    image:
      "https://cdn.igp.com/f_auto,q_auto,t_pnopt12prodlp/products/p-guardians-of-the-galaxy-jigsaw-puzzle-205615-m.jpg",
    name: "Guardians of the Galaxy Jigsaw Puzzle",
    reviews: 40,
    rating: 4.2,
    price: "595",
    discount: 30,
    categoryName: "birthday",
    newArrival: true,
    trending: false,
  },
];
